export const PRODUCTS = [
  {
    id: '1',
    name: 'Quantum X Pro',
    brand: 'Nexus',
    price: 999,
    image: { uri: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=600&q=80' },
    featured: true,
    ram: '12GB',
    storage: '256GB',
    description: 'The ultimate smartphone experience with cutting-edge technology and unparalleled performance.',
    specs: {
      display: '6.7" AMOLED 120Hz',
      processor: 'Quantum X3',
      ram: '12GB LPDDR5',
      storage: '256GB UFS 3.1',
      camera: '108MP + 12MP + 8MP',
      battery: '5000mAh',
    }
  },
  {
    id: '2',
    name: 'Galaxy Z Ultra',
    brand: 'Samsung',
    price: 1199,
    image: { uri: 'https://images.unsplash.com/photo-1610792516307-ea5acd9c3b00?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=600&q=80' },
    featured: true,
    ram: '16GB',
    storage: '512GB',
    description: 'Foldable display with revolutionary design and flagship performance.',
    specs: {
      display: '7.6" Foldable Dynamic AMOLED',
      processor: 'Snapdragon 8 Gen 2',
      ram: '16GB LPDDR5X',
      storage: '512GB UFS 4.0',
      camera: '200MP + 12MP + 10MP',
      battery: '4400mAh',
    }
  },
  {
    id: '3',
    name: 'iPhone 15 Pro Max',
    brand: 'Apple',
    price: 1299,
    image: { uri: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=600' },
    featured: true,
    ram: '8GB',
    storage: '1TB',
    description: 'The most powerful iPhone with titanium design and advanced camera system.',
    specs: {
      display: '6.7" Super Retina XDR',
      processor: 'A17 Pro',
      ram: '8GB',
      storage: '1TB NVMe',
      camera: '48MP + 12MP + 12MP',
      battery: '4422mAh',
    }
  },
  {
    id: '4',
    name: 'Pixel 8 Pro',
    brand: 'Google',
    price: 899,
    image: { uri: 'https://images.pexels.com/photos/47261/pexels-photo-47261.jpeg?auto=compress&cs=tinysrgb&w=600' },
    featured: false,
    ram: '12GB',
    storage: '256GB',
    description: 'AI-powered smartphone with best-in-class computational photography.',
    specs: {
      display: '6.7" LTPO OLED',
      processor: 'Google Tensor G3',
      ram: '12GB LPDDR5',
      storage: '256GB UFS 3.1',
      camera: '50MP + 48MP + 48MP',
      battery: '5050mAh',
    }
  },
  {
    id: '5',
    name: 'OnePlus 11',
    brand: 'OnePlus',
    price: 699,
    image: { uri: 'https://images.unsplash.com/photo-1555774698-0b77e0d5fac6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=600&q=80' },
    featured: false,
    ram: '16GB',
    storage: '256GB',
    description: 'Flagship killer with Hasselblad camera and blazing fast performance.',
    specs: {
      display: '6.7" Fluid AMOLED',
      processor: 'Snapdragon 8 Gen 2',
      ram: '16GB LPDDR5X',
      storage: '256GB UFS 4.0',
      camera: '50MP + 48MP + 32MP',
      battery: '5000mAh',
    }
  },
  {
    id: '6',
    name: 'Xperia 1 V',
    brand: 'Sony',
    price: 1099,
    image: { uri: 'https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=600' },
    featured: false,
    ram: '12GB',
    storage: '512GB',
    description: 'Professional-grade camera phone with 4K OLED display.',
    specs: {
      display: '6.5" 4K OLED',
      processor: 'Snapdragon 8 Gen 2',
      ram: '12GB LPDDR5',
      storage: '512GB UFS 4.0',
      camera: '48MP + 12MP + 12MP',
      battery: '5000mAh',
    }
  },
  {
    id: '7',
    name: 'ROG Phone 7',
    brand: 'ASUS',
    price: 999,
    image: { uri: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=600&q=80' },
    featured: true,
    ram: '16GB',
    storage: '512GB',
    description: 'Gaming smartphone with ultra-fast refresh rate and cooling system.',
    specs: {
      display: '6.78" AMOLED 165Hz',
      processor: 'Snapdragon 8 Gen 2',
      ram: '16GB LPDDR5X',
      storage: '512GB UFS 4.0',
      camera: '50MP + 13MP + 5MP',
      battery: '6000mAh',
    }
  },
  {
    id: '8',
    name: 'Redmi Note 12 Pro',
    brand: 'Xiaomi',
    price: 399,
    image: { uri: 'https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&w=600' },
    featured: false,
    ram: '8GB',
    storage: '128GB',
    description: 'Budget flagship with impressive camera and battery life.',
    specs: {
      display: '6.67" AMOLED',
      processor: 'Dimensity 1080',
      ram: '8GB LPDDR4X',
      storage: '128GB UFS 2.2',
      camera: '50MP + 8MP + 2MP',
      battery: '5000mAh',
    }
  }
];